---
- name: Genrate nginx configuration
  template: src=goapp.j2 dest=/home/{{ ansible_ssh_user }}/goapp.conf

- name: Start docker web instances
  docker:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "/home/{{ ansible_ssh_user }}/goapp.conf:/etc/nginx/conf.d/default.conf"
