---
- name: Install docker daemon
  yum: name=docker state=present

- name: Install docker-py for docker modules
  pip: name=docker-py version=1.6.0 

- name: Startup docker and enable at startup
  service: name=docker state=started enabled=yes
