---
- hosts: tag_Function_goapp;tag_Function_web
  gather_facts: no
  connection: local
  tasks:
    - wait_for: port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH timeout=500

- hosts: tag_Function_goapp;tag_Function_web
  sudo: yes
  roles:
    - docker

- hosts: tag_Function_goapp
  sudo: yes
  serial: 1
  roles:
    - goapp

- hosts: tag_Function_web
  sudo: yes
  roles:
    - nginx
